In [1]:
import numpy as np  #导入numpy库

arr1 = np.array([1,2,3,4]) #创建一个数组

print("创建的数组是：",arr1)

创建的数组是： [1 2 3 4]


In [2]:
#创建一个二维数组
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("创建的二维数组是：\n",arr2)

创建的二维数组是：
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
#输出数组的维度
print("数组的维度是：",arr2.shape)

数组的维度是： (3, 4)


In [8]:
print("数组的类型是：",arr2.dtype)

数组的类型是： int32


In [9]:
print("数组的元素个数是：",arr2.size)

数组的元素个数是： 12


In [10]:
print("每个元素的大小是：",arr2.itemsize)

每个元素的大小是： 4


In [12]:
#重新设置二维数组的shape
arr2.shape = (4,3)
print("重置后的二维数组：\n",arr2)

重置后的二维数组：
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
print("使用arange函数创建的数组为：\n",np.arange(0,1,0.1))    # 此处的0.1表示步长

使用arange函数创建的数组为：
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [15]:
print("使用linspace函数创建的数组为：\n",np.linspace(0,1,12)) # 此处的12表示数组的元素个数

使用linspace函数创建的数组为：
 [0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


In [17]:
print("使用linspace函数创建的数组为：\n",np.linspace(0,1,3))  # 此处的3表示数组的元素个数

使用linspace函数创建的数组为：
 [0.  0.5 1. ]


In [18]:
print("使用logspace函数创建的数组为：\n",np.logspace(0,2,10))  # 此处的0、2代表指数，底数为10

使用logspace函数创建的数组为：
 [  1.           1.66810054   2.7825594    4.64158883   7.74263683
  12.91549665  21.5443469   35.93813664  59.94842503 100.        ]


In [21]:
print("使用zeros函数创建的全为0的数组：\n",np.zeros((3,3)))

使用zeros函数创建的全为0的数组：
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
print("使用ones函数创建的全为1的数组：\n",np.ones((3,3)))

使用ones函数创建的全为1的数组：
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
print("使用eye函数创建的主对角线上元素为1的数组：\n",np.eye(4))

使用eye函数创建的主对角线上元素为1的数组：
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
print("使用diag函数创建的除对角线外均为0的数组：\n",np.diag([1,2,3,4]))
print("使用diag函数创建的除对角线外均为0的数组：\n",np.diag([0,1,2,3,4,0])) # 对角线上的数也可以是0

使用diag函数创建的除对角线外均为0的数组：
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
使用diag函数创建的除对角线外均为0的数组：
 [[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 0]]
