In [29]:
import numpy as np

a = np.arange(12)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [32]:
b = a.reshape(3,4)
print(arr)
print(arr.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2


In [33]:
a[0]=111
print(a,"\n",b)

[111   1   2   3   4   5   6   7   8   9  10  11] 
 [[111   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [39]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [36]:
print(a.ravel())
print(a.flatten())
print(a.flatten('F'))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [8]:
m = np.arange(12).reshape(4,3)
n = m*3
print("m:\n",m)
print("n:\n",n)

m:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
n:
 [[ 0  3  6]
 [ 9 12 15]
 [18 21 24]
 [27 30 33]]


In [9]:
print("横向组合：\n",np.hstack((m,n)))
print("纵向组合：\n",np.vstack((m,n)))

横向组合：
 [[ 0  1  2  0  3  6]
 [ 3  4  5  9 12 15]
 [ 6  7  8 18 21 24]
 [ 9 10 11 27 30 33]]
纵向组合：
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [ 0  3  6]
 [ 9 12 15]
 [18 21 24]
 [27 30 33]]


In [10]:
print("横向组合：\n",np.concatenate((m,n),axis=1))
print("纵向组合：\n",np.concatenate((m,n),axis=0))

横向组合：
 [[ 0  1  2  0  3  6]
 [ 3  4  5  9 12 15]
 [ 6  7  8 18 21 24]
 [ 9 10 11 27 30 33]]
纵向组合：
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [ 0  3  6]
 [ 9 12 15]
 [18 21 24]
 [27 30 33]]


In [41]:
# 数组的组合
import numpy as np

a = np.arange(24).reshape(4,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [43]:
print(np.hsplit(a,[4]))

[array([[ 0,  1,  2,  3],
       [ 6,  7,  8,  9],
       [12, 13, 14, 15],
       [18, 19, 20, 21]]), array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23]])]


In [11]:
print(np.vsplit(a,2))

[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])]


In [12]:
print(np.split(a,3,axis=1))

[array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]]), array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23]])]


In [23]:
print(np.split(a,2,axis=0))

[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])]


In [25]:
print(np.split(a,[1],axis=0))

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])]


In [14]:
c = np.arange(48).reshape(3,4,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


In [16]:
print(np.dsplit(c,2))

[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]],

       [[16, 17],
        [20, 21],
        [24, 25],
        [28, 29]],

       [[32, 33],
        [36, 37],
        [40, 41],
        [44, 45]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]],

       [[18, 19],
        [22, 23],
        [26, 27],
        [30, 31]],

       [[34, 35],
        [38, 39],
        [42, 43],
        [46, 47]]])]


In [22]:
np.dsplit(c,[3])

[array([[[ 0,  1,  2],
         [ 4,  5,  6],
         [ 8,  9, 10],
         [12, 13, 14]],
 
        [[16, 17, 18],
         [20, 21, 22],
         [24, 25, 26],
         [28, 29, 30]],
 
        [[32, 33, 34],
         [36, 37, 38],
         [40, 41, 42],
         [44, 45, 46]]]),
 array([[[ 3],
         [ 7],
         [11],
         [15]],
 
        [[19],
         [23],
         [27],
         [31]],
 
        [[35],
         [39],
         [43],
         [47]]])]