In [39]:
import numpy as np

arr = np.arange(100).reshape(10,10)
np.save("tmpsave/save_arr",arr)
print("保存的数组：\n",arr)

保存的数组：
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [36]:
import numpy as np

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.arange(0.0,1.0,0.1)
np.savez("tmpsave/savez_ab",arr1,arr2)
print("保存的数组a：\n",arr1)
print("保存的数组b：\n",arr2)

保存的数组a：
 [[1 2 3]
 [4 5 6]]
保存的数组b：
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [8]:
import numpy as np
loaded_data = np.load("tmpsave/save_arr.npy") #读取含有单个数组的文件
print("读取的文件数组为：\n",loaded_data)

读取的文件数组为：
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [38]:
loaded_data1 = np.load("tmpsave/savez_ab.npz") #读取含有多个数组的文件
print("读取的文件数组arr1\n",loaded_data1['arr_0'])
print("读取的文件数组arr2\n",loaded_data1['arr_1'])

读取的文件数组arr1
 [[1 2 3]
 [4 5 6]]
读取的文件数组arr2
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [40]:
import numpy as np

arr = np.arange(0,12,0.5).reshape(4,-1)
print("创建的数组是：\n",arr)

创建的数组是：
 [[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]


In [42]:
np.savetxt("tmpsave/arr.txt",arr,fmt="%d",delimiter=",") #fmt="%d"表示保存为整数，delimiter=","表示以指定的逗号隔开

In [43]:
loaded_data = np.loadtxt("tmpsave/arr.txt",delimiter=",")
print("读取的数组为：\n",loaded_data)

读取的数组为：
 [[ 0.  0.  1.  1.  2.  2.]
 [ 3.  3.  4.  4.  5.  5.]
 [ 6.  6.  7.  7.  8.  8.]
 [ 9.  9. 10. 10. 11. 11.]]


In [44]:
loaded_data = np.genfromtxt("tmpsave/arr.txt",delimiter=",")
print("读取的数组为：\n",loaded_data)

读取的数组为：
 [[ 0.  0.  1.  1.  2.  2.]
 [ 3.  3.  4.  4.  5.  5.]
 [ 6.  6.  7.  7.  8.  8.]
 [ 9.  9. 10. 10. 11. 11.]]


In [6]:
import numpy as np
a = np.mat(np.arange(1,5).reshape(2,2))
b = np.mat(np.arange(4,8).reshape(2,2))
print(a)
print(b)

[[1 2]
 [3 4]]
[[4 5]
 [6 7]]


In [7]:
print(a*b)

[[16 19]
 [36 43]]
