In [1]:
import numpy as np 

matr1 = np.mat("1 2 3;4 5 6;7 8 9") #使用分号隔开数据
print("创建的矩阵为：\n",matr1)

创建的矩阵为：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
matr2 = np.matrix([[1,2,3],[4,5,6],[6,7,8]])
print("创建的矩阵为：\n",matr2)

创建的矩阵为：
 [[1 2 3]
 [4 5 6]
 [6 7 8]]


In [4]:
matr3 = np.matrix([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])
matr4 = matr3.reshape(3,4)
print("创建的矩阵为：\n",matr3)
print("修改后的矩阵是：\n",matr4)

创建的矩阵为：
 [[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]]
修改后的矩阵是：
 [[ 1  2  3  4]
 [ 5  6  6  7]
 [ 8  9 10 11]]


In [5]:
matr4[0,0]=100
print(matr3)

[[100   2   3]
 [  4   5   6]
 [  6   7   8]
 [  9  10  11]]


In [8]:
# bmat 创建矩阵
arr1 = np.eye(3)
arr2 = arr1*3
print(arr1)
print(arr2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]


In [12]:
print("创建的矩阵是：\n",np.bmat("arr1 arr2 arr1;arr2 arr1 arr2"))

创建的矩阵是：
 [[1. 0. 0. 3. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 3. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 3. 0. 0. 1.]
 [3. 0. 0. 1. 0. 0. 3. 0. 0.]
 [0. 3. 0. 0. 1. 0. 0. 3. 0.]
 [0. 0. 3. 0. 0. 1. 0. 0. 3.]]


In [14]:
# 矩阵的计算
a = np.mat("1 2 3;4 5 6;7 8 9")
b = a*2
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [18]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]
[[ 60  72  84]
 [132 162 192]
 [204 252 300]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [20]:
mart1 = np.mat(np.arange(12).reshape(3,4))
print(matr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
print("转置：\n",matr1.T)

转置：
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [23]:
print("共轭转置：\n",matr1.H)

共轭转置：
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [24]:
print("逆矩阵：\n",matr1.I)

逆矩阵：
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [25]:
print("矩阵的二维数组：\n",matr1.A)

矩阵的二位数组：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x)
print(y)

[1 2 3]
[4 5 6]


In [4]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**y)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [6]:
print(x>y)
print(x>=y)
print(x<y)
print(x<=y)
print(x==y)
print(x!=y)
print(np.all(x==y))
print(np.any(x!=y))

[False False False]
[False False False]
[ True  True  True]
[ True  True  True]
[False False False]
[ True  True  True]
False
True


In [3]:
# 广播机制
import numpy as np
a = np.array([[0,0,0],[1,1,1],[2,2,2],[3,3,3]])
print("a:\n",a)

a:
 [[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]


In [4]:
print(a.shape)

(4, 3)


In [5]:
b = np.array([1,2,3])
print("b:\n",b)

b:
 [1 2 3]


In [6]:
print(b.shape)

(3,)


In [7]:
print(a+b)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [8]:
c = np.array([1,2,3,4]).reshape(4,1)
print(c)

[[1]
 [2]
 [3]
 [4]]


In [9]:
print(a+c)

[[1 1 1]
 [3 3 3]
 [5 5 5]
 [7 7 7]]
