In [2]:
import numpy as np 
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(arr[5])      #第五个
print(arr[1:8])    #1-7
print(arr[:5])     #0-4
print(arr[1:9:2])  #1-8每两个取一个，从前往后
print(arr[-1])     #最后一个
print(arr[5:1:-2]) #5-1每两个取一个，从后往前

5
[1 2 3 4 5 6 7]
[0 1 2 3 4]
[1 3 5 7]
9
[5 3]


In [4]:
arr1 = np.arange(12).reshape(3,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
print(arr1[0,2:4]) 

[2 3]


In [7]:
print(arr1[1:,2:])

[[ 6  7]
 [10 11]]


In [8]:
print(arr1[:,2])

[ 2  6 10]


In [10]:
print(arr1[(0,1,2),(1,2,3)])

[ 1  6 11]


In [12]:
print(arr1[1:,(0,2,3)])

[[ 4  6  7]
 [ 8 10 11]]


In [14]:
mask = np.array([1,0,1],dtype=np.bool)
print(arr1[mask,2])

[ 2 10]
