In [23]:
from sklearn.datasets import load_breast_cancer
from sklearn.datasets import load_iris
from sklearn.datasets import load_wine
from sklearn.datasets import load_digits
from sklearn.datasets import load_boston
from sklearn.datasets import fetch_california_housing

cancer = load_breast_cancer() # 将数据集赋值给cancer变量
print('breast_cancer数据集的长度为：\n',len(cancer))
print('breast_cancer数据集的类型为：\n',type(cancer))

iris = load_iris() # 将数据集赋值给iris变量
print('iris数据集的长度为：\n',len(iris))
print('iris数据集的类型为：\n',type(iris))

wine = load_wine() # 将数据集赋值给wine变量
print('wine数据集的长度为：\n',len(wine))
print('wine数据集的类型为：\n',type(wine))

digits = load_digits() # 将数据集赋值给digits变量
print('digits数据集的长度为：\n',len(digits))
print('digits数据集的类型为：\n',type(digits))

boston = load_boston() # 将数据集赋值给boston变量
print('boston数据集的长度为：\n',len(boston))
print('boston数据集的类型为：\n',type(boston))

fetch_california_housing = fetch_california_housing() # 将数据集赋值给fetch_california_housing变量
print('fetch_california_housing数据集的长度为：\n',len(fetch_california_housing))
print('fetch_california_housing数据集的类型为：\n',type(fetch_california_housing))

breast_cancer数据集的长度为：
 6
breast_cancer数据集的类型为：
 <class 'sklearn.utils.Bunch'>
iris数据集的长度为：
 6
iris数据集的类型为：
 <class 'sklearn.utils.Bunch'>
wine数据集的长度为：
 5
wine数据集的类型为：
 <class 'sklearn.utils.Bunch'>
digits数据集的长度为：
 5
digits数据集的类型为：
 <class 'sklearn.utils.Bunch'>
boston数据集的长度为：
 5
boston数据集的类型为：
 <class 'sklearn.utils.Bunch'>
fetch_california_housing数据集的长度为：
 4
fetch_california_housing数据集的类型为：
 <class 'sklearn.utils.Bunch'>


In [25]:
cancer_data = cancer['data']
print('breast_cancer数据集的数据为：\n',cancer_data)
iris_data = iris['data']
print('iris数据集的数据为：\n',iris_data)
wine_data = wine['data']
print('wine数据集的数据为：\n',wine_data)
digits_data = digits['data']
print('digits数据集的数据为：\n',digits_data)
boston_data = boston['data']
print('boston数据集的数据为：\n',boston_data)
fetch_california_housing_data = fetch_california_housing['data']
print('fetch_california_housing数据集的数据为：\n',fetch_california_housing_data)

breast_cancer数据集的数据为：
 [[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
iris数据集的数据为：
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.

In [26]:
cancer_target = cancer['target'] # 取出数据集的标签
print('breast_cancer数据集的标签为：\n',cancer_target)
iris_target = iris['target'] # 取出数据集的标签
print('iris数据集的标签为：\n',iris_target)
wine_target = wine['target'] # 取出数据集的标签
print('wine数据集的标签为：\n',wine_target)
digits_target = digits['target'] # 取出数据集的标签
print('digits数据集的标签为：\n',digits_target)
boston_target = boston['target'] # 取出数据集的标签
print('boston数据集的标签为：\n',boston_target)
fetch_california_housing_target = fetch_california_housing['target'] # 取出数据集的标签
print('fetch_california_housing数据集的标签为：\n',fetch_california_housing_target)

breast_cancer数据集的标签为：
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1

In [31]:
cancer_names = cancer['feature_names'] # 取出数据集的特征名
print('breast_names数据集的特征名为：\n',cancer_names)
iris_names = iris['feature_names']  # 取出数据集的特征名
print('iris数据集的特征名为：\n',iris_names)
wine_names = wine['feature_names']  # 取出数据集的特征名
print('wine数据集的特征名为：\n',wine_names)
# digits_names = digits['feature_names']  # 取出数据集的特征名
# print('digits数据集的特征名为：\n',digits_names)
boston_names = boston['feature_names']  # 取出数据集的特征名
print('boston数据集的特征名为：\n',boston_names)
fetch_california_housing_names = fetch_california_housing['feature_names']  # 取出数据集的特征名
print('fetch_california_housing数据集的特征名为：\n',fetch_california_housing_names)

breast_names数据集的特征名为：
 ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
iris数据集的特征名为：
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
wine数据集的特征名为：
 ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
boston数据集的特征名为：
 ['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LST

In [32]:
cancer_desc = cancer['DESCR'] # 取出数据集的描述信息
print('breast_names数据集的描述信息为：\n',cancer_desc )
print('*'*100)
iris_desc  = iris['DESCR']  # 取出数据集的描述信息
print('iris数据集的描述信息为：\n',iris_desc )
print('*'*100)
wine_desc  = wine['DESCR']  # 取出数据集的描述信息
print('wine数据集的描述信息为：\n',wine_desc )
print('*'*100)
digits_desc  = digits['DESCR'] # 取出数据集的描述信息
print('digits数据集的描述信息为：\n',digits_desc )
print('*'*100)
boston_desc  = boston['DESCR']  # 取出数据集的描述信息
print('boston数据集的描述信息为：\n',boston_desc )
print('*'*100)
fetch_california_housing_desc  = fetch_california_housing['DESCR']  # 取出数据集的描述信息
print('fetch_california_housing数据集的描述信息为：\n',fetch_california_housing_desc )

breast_names数据集的描述信息为：
 .. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, f

In [33]:
print('原始数据集数据的形状为：',cancer_data.shape)
print('原始数据集标签的形状为：',cancer_target.shape)

原始数据集数据的形状为： (569, 30)
原始数据集标签的形状为： (569,)


In [35]:
from sklearn.model_selection import train_test_split

cancer_data_train,cancer_data_test,cancer_target_train,cancer_target_test = train_test_split(cancer_data,cancer_target,
                                                                                             test_size=0.2,random_state=42)
print('训练集数据的形状为：',cancer_data_train.shape)
print('训练集数据的标签形状为：',cancer_target_train.shape)
print('测试集数据的形状为：',cancer_data_test.shape)
print('测试集数据的标签形状为：',cancer_target_test.shape)

训练集数据的形状为： (455, 30)
训练集数据的标签形状为： (455,)
测试集数据的形状为： (114, 30)
测试集数据的标签形状为： (114,)


In [37]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# 生成规则
Scaler = MinMaxScaler().fit(cancer_data_train)
# 将规则应用于训练集
cancer_trainScaler = Scaler.transform(cancer_data_train)
# 将规则应用于测试集
cancer_testScaler = Scaler.transform(cancer_data_test)
print('离差标准化前训练集数据的最小值：',cancer_data_train.min())
print('离差标准化后训练集数据的最小值：',np.min(cancer_trainScaler))
print('离差标准化前训练集数据的最大值：',np.max(cancer_data_train))
print('离差标准化后训练集数据的最大值：',np.max(cancer_trainScaler))
print('离差标准化前测试集数据的最小值：',np.min(cancer_data_test))
print('离差标准化后测试集数据的最小值：',np.min(cancer_testScaler))
print('离差标准化前测试集数据的最大值：',np.max(cancer_data_test))
print('离差标准化后测试集数据的最大值：',np.max(cancer_testScaler))

离差标准化前训练集数据的最小值： 0.0
离差标准化后训练集数据的最小值： 0.0
离差标准化前训练集数据的最大值： 4254.0
离差标准化后训练集数据的最大值： 1.0000000000000002
离差标准化前测试集数据的最小值： 0.0
离差标准化后测试集数据的最小值： -0.057127602776294695
离差标准化前测试集数据的最大值： 3432.0
离差标准化后测试集数据的最大值： 1.3264399566986453


In [42]:
from sklearn.decomposition import PCA
 
# 生成规则
pca_model=PCA(n_components=10).fit(cancer_trainScaler)
# 将规则应用到训练集
cancer_trainPca = pca_model.transform(cancer_trainScaler)
# 将规则应用到测试集
cancer_testPca = pca_model.transform(cancer_testScaler)
print('PCA降维前训练集数据的形状为：',cancer_trainScaler.shape)
print('PCA降维后训练集数据的形状为：',cancer_trainPca.shape)
print('PCA降维前测试集数据的形状为：',cancer_testScaler.shape)
print('PCA降维后测试集数据的形状为：',cancer_testPca.shape)

PCA降维前训练集数据的形状为： (455, 30)
PCA降维后训练集数据的形状为： (455, 10)
PCA降维前测试集数据的形状为： (114, 30)
PCA降维后测试集数据的形状为： (114, 10)


In [ ]:
from sklearn